---

services:
  sonarr:
    image: linuxserver/sonarr:develop
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=9000
      - UMASK=002
      - TZ=Asia/Kolkata
      - SONARR_BRANCH=develop
    volumes:
      - ~/docker/data/config/sonarr:/config
      - ~/docker/data/media/tv:/tv
      - ~/docker/data/qBittorrent:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - arr


networks:
  arr:
    external: true



