---

services:
  sonarr:
    image: linuxserver/sonarr:develop
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=9000
      - UMASK=002
      - UMASK_SET=002
      - TZ=Asia/Kolkata
      - SONARR_BRANCH=develop
    env_file:
      - .env
    volumes:
      - $CONFIG:/config
      - $TV:/tv
      - $DOWNLOADS:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - arr


networks:
  arr:
    external: true





