---

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - SONARR_BRANCH=latest
    volumes:
      - ~/docker/data/config/sonarr:/config
      - ~/docker/data/media/tv:/tv
      - ~/docker/data/qBittorrent:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - arr


networks:
  arr:
    external: true



