---
version: '3.3'

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: Sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - SONARR_BRANCH=latest
    volumes:
      - /Servarr/Config/Sonarr:/config
      - /srv/1.4TB/Servarr/media/tv:/tv
      - /srv/1.4TB/Servarr/qBittorrent/tv:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - arr_stack
      - traefik_backend


networks:
  arr_stack:
    external:
      name: arr_stack
  traefik_backend:
    external:
      name: traefik_backend


