---

services:

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent

    environment:
      - PUID=0
      - PGID=0
      - UMASK=002
      - UMASK_SET=002
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8084
      - TORRENTING_PORT=6881

    volumes:
      - ~/Server/appdata/qbittorrent:/config
      - /mnt/mergerfs_storage/mergerfs_data:/data 


    ports:
      - 8084:8084             # WEBUI_PORT:WEBUI_PORT
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - arr


networks:
  arr:
    external: true
