---

services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    env_file:
      - .env
    environment:
      - PUID=0
      - PGID=9000
      - UMASK=002
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8084
      - TORRENTING_PORT=6881
    volumes:
      - ~/docker/data/config/qbittorrent:/config
      - ~/docker/data/qBittorrent:/downloads
    ports:
      - 8084:8084 # WEBUI_PORT:WEBUI_PORT
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - arr
#        ipv4_address: 172.18.0.17



networks:
  arr:
    external: true


