---

services:
  postgres:
    image: postgres:17  # Or your desired version
    container_name: postgresql
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready" # Use pg_isready to check if DB is ready


volumes:
  db_data:
    external: true


