services:

  filebrowser:
    image: gtstef/filebrowser:stable-slim
    user: "0:0"
    command: ["--config", "/home/filebrowser/data/config.yaml"]
    
    volumes:
      - /data:/mergerfs_data
      - /host_opt:/host_opt
      - /host_opt/appdata/filebrowser-quantum:/home/filebrowser/data

      # direct drives
      - /media/drive/1.4TB:/media/drive/1.4TB
      - /media/drive/300G:/media/drive/300G
      - /media/drive/500G:/media/drive/500G


    networks:
      - proxy

    ports:
      - 8082:80 # exposes port 80 to host, the left-side number can be changed without config.yaml changes.

    restart: unless-stopped


networks:
  proxy:
    external: true






