
---

services:
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=9000
      - UMASK=002
      - TZ=Asia/Kolkata
    volumes:
      - ~/docker/data/config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      arr:
        ipv4_address: 172.18.0.16


networks:
  arr:
    external: true


