
---
version: '3'

services:
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: Prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /Servarr/Config/Prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - arr_stack
      - traefik_backend
    


networks:
  arr_stack:
    external:
      name: arr_stack
  traefik_backend:
    external:
      name: traefik_backend


