---

services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    restart: unless-stopped
    ports:
      - 8082:80
#    environment:
#      - PGID=${PGID}
#      - PUID=${PUID}
    volumes:
      - ~/docker/data/config/filebrowser:/config
      - ~/docker/data/config/filebrowser:/database
      - ~/docker/data:/srv

    networks:
      - proxy


networks:
  proxy:
    external: true



