---

services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    restart: unless-stopped
    ports:
      - 8082:80
    env_file:
      - .env
#    environment:
#      - PGID=${PGID}
#      - PUID=${PUID}
    volumes:
      - $CONFIG:/config
      - $DB:/database
      - $DATA:/srv

    networks:
      - proxy


networks:
  proxy:
    external: true



