---

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    command:
      - "--storage.tsdb.retention.time=24h"  # retain for 24 hr
      - "--storage.tsdb.path=/prometheus"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Custom Prometheus config file
      - ./prometheus.yml:/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"  # Prometheus web UI

    networks:
      - tailscale
    restart: unless-stopped

volumes:
    prometheus_data:
      external: true

networks:
  tailscale:
    external: true

