
---
#version: '3'

services:

  postgresql:
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_DB=keycloak
      - POSTGRES_PASSWORD=keycloak_password
#      - PUID=0
#      - GUID=0
    volumes:
#      - ~/docker/data/config/keycloak/postgresql_data:/var/lib/postgresql/data
      - ./postgresql_data:/var/lib/postgresql/data

    restart: unless-stopped
    networks:
      - proxy


  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    restart: unless-stopped
    command: start
    networks:
      - proxy
    depends_on:
      - postgresql
    ports:
      - 9080:8080
    environment:
      - KC_PROXY_ADDRESS_FORWARDING=true
      - KC_HOSTNAME_STRICT=false
#      - KC_HOSTNAME=
      - KC_PROXY=edge
      - KC_HTTP_ENABLED=true
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak_password
      - KC_DB_URL_HOST=postgresql
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=keycloak
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

    labels:
      - tsdproxy.enable=true    # labels for tsdproxy
      - tsdproxy.name=keycloak
      - tsdproxy.container_port=9080
      - tsdproxy.ephemeral=true


networks:
  proxy:
    external: true


