---

services:
  radarr:
    image: ghcr.io/hotio/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - UMASK=002
      - TZ=Asia/Kolkata
    volumes:
      - /host_opt/appdata/radarr:/config
      - /data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - arr

networks:
  arr:
    external: true

