---

services:
  radarr:
    image: linuxserver/radarr:develop
    container_name: radarr
    environment:
      - PUID=0
      - PGID=9000
      - UMASK=002
      - TZ=Asia/Kolkata
    env_file:
      - .env
    volumes:
      - $CONFIG:/config
      - $MOVIES:/movies
      - $DOWNLOADS:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - arr

networks:
  arr:
    external: true

