---

services:
  radarr:
    image: linuxserver/radarr:develop
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
    volumes:
      - ~/docker/data/config/radarr:/config
      - ~/docker/data/media/movies:/movies
      - ~/docker/data/qBittorrent:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - arr

networks:
  arr:
    external: true


