---

services:
  webdav:
    image: arun912/apache2-webdav:0.0.2
    restart: unless-stopped
    user: "0:9000"
    ports:
      - "8085:80"
    env_file:
      - .env
    volumes:
      - $STORAGE:/var/www/webdav

    networks:
      - proxy

networks:
  proxy:
    external: true

