---

services:
  mazanoke:
    container_name: mazanoke
    image: ghcr.io/civilblur/mazanoke:latest
    restart: unless-stopped
    ports:
      - "3474:80"

    networks:
      - proxy


networks:
  proxy:
    external: true



