---

version: "3"

services:
  agent:
    image: portainer/agent:latest
    volumes:
      - /:/host
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    container_name: portainer_agent
    ports:
      - 9001:9001

