
---
version: '3'

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  adguard:
    image: adguard/adguardhome
    container_name: AdGuardHome
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - 53:53/tcp
      - 53:53/udp
      # - 67:67/udp     # DHCP
      # - 68:68/udp     # DHCP
      
      - 8880:80/tcp
      - 4443:443/tcp
      - 4443:443/udp
      - 3000:3000/tcp
      # - 853:853/tcp   #DNS over TLS
      # - 853:853/udp   #DNS over TLS
      - 784:784/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
      # - 67:67/udp # Only required if you are using AdGuardHome as your DHCP server

    environment:
      TZ: Asia/Kolkata
      # WEBPASSWORD: root123
    # Volumes store your data between container upgrades
    volumes:
      - /Servarr/Config/AdGuardHome:/opt/adguardhome/work
      - /Servarr/Config/AdGuardHome:/opt/adguardhome/conf
    

    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #   - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    
    restart: unless-stopped
    networks:
      - backend


networks:
  backend:
    external:
      name: traefik_backend
