---

services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguard-home
#    env_file:
#      - .env
    user: "0:0"
    network_mode: host
#    ports:
#      - 53:53/tcp
#      - 53:53/udp
#      - 784:784/udp    # DNS-over-QUIC
#      - 853:853/tcp    # DNS-over-TLS
#      - 3000:3000/tcp  # admin panel
#      - 80:80/tcp
#      - 443:443/tcp
    volumes:
      - ~/Server/appdata/adguardhome/work:/opt/adguardhome/work
      - ~/Server/appdata/adguardhome/conf:/opt/adguardhome/conf
    restart: unless-stopped

