---

services:

  jellyfin:

    image: ghcr.io/hotio/jellyfin:latest
    container_name: Jellyfin
    user: "0:0"
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
      - UMASK=002
      - WEBUI_PORTS=8096/tcp
      # - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - JELLYFIN_PublishedServerUrl=192.168.1.31 #optional
    # env_file:
    #   - .env
    volumes: 
      - /mnt:/mnt
      - ~/Server/appdata/jellyfin:/config
    ports:
      - 8096:8096
      # - 8920:8920 # https
      - 7359:7359/udp #optional
      # - 1900:1900/udp #optional

    devices:
      # This passes the Intel GPU into the container
      # - /dev/dri/card1:/dev/dri/card1
      # - /dev/dri/renderD128:/dev/dri/renderD128

      # pass the entire directory
      - /dev/dri:/dev/dri

    restart: unless-stopped

