---

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: Jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
      # - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - JELLYFIN_PublishedServerUrl=192.168.1.4 #optional
    env_file:
      - .env
    volumes:
      #- /Servarr/Config/Jellyfin:/config
      #- jellyfin:/config
      - ./config:/config
      - $TV:/data/tvshows
      - $MOVIES:/data/movies
      - $ANIME:/data/anime
    ports:
      - 8096:8096
      # - 8920:8920 # https
      # - 7359:7359/udp #optional
      # - 1900:1900/udp #optional

    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.jellyfin.entrypoints=web"  # 80
    #   - "traefik.http.routers.jellyfin.rule=Host(`nano.chaco-climb.ts.net`)"
    #   - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

    restart: unless-stopped
    networks:
      - arr_stack
      - traefik_backend


networks:
  arr_stack:
    external:
      name: arr_stack
  traefik_backend:
    external:
      name: traefik_backend


volumes: 
  jellyfin:
    external:
      name: jellyfin
