---

services:
  seerr:
    image: ghcr.io/hotio/seerr:latest
    container_name: jellyseerr
    user: 0:0
    environment:
      - LOG_LEVEL=info
      - TZ=Asia/Kolkata
      - PUID=0
      - PGID=0
      - UMASK=002
    ports:
      - 5055:5055
    volumes:
      - /host_opt/appdata/seerr:/app/config
    restart: unless-stopped
    networks:
      - arr


networks:
  arr:
    external: true

