---

services:
  ariang:
    image: hurlenko/aria2-ariang
    ports:
      - 8888:8080
    env_file:
      - .env
    volumes:
      - $DATA:/aria2/data
      - $CONF:/aria2/conf
    environment:
      - PUID=0
      - PGID=9000
      - RPC_SECRET=secret
      - ARIA2RPCPORT=8888
    restart: always
