---

services:

  kodbox:
    image: arun912/kodbox-apache2:0.0.2
    container_name: kodbox
    restart: unless-stopped
    volumes:
      - ./media/drive:/opt/storage
#      - ./site:/var/www/kodbox/data
    ports:
      - "8083:80"

    networks:
      - proxy

networks:
  proxy:
    external: true

