---
version: '3'

services:
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: Flare_Solverr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    volumes:
      - ./config:/config
    ports:
      - 8191:8191
    restart: unless-stopped
#    networks:
#     - arr_stack
#      - traefik_backend



#networks:
#  arr_stack:
#    external:
#      name: arr_stack
#  traefik_backend:
#    external:
#      name: traefik_backend
