---

services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    hostname: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/docker/data/config/tsdproxy:/data
    restart: unless-stopped
    environment:
      - TSDPROXY_AUTHKEY=${TSDPROXY_AUTHKEY}
      - TSDPROXY_HOSTNAME=172.17.0.1
      - DOCKER_HOST=unix:///var/run/docker.sock
    env_file:
      - .env

    networks:
      - proxy


networks:
  proxy:
    external: true


