---


services:
  jellyseerr:
    image: ghcr.io/hotio/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
      - TZ=Asia/Kolkata
    ports:
      - 5055:5055
    volumes:
      - ~/docker/data/config/jellyseerr:/app/config
    restart: unless-stopped
    networks:
      - arr


networks:
  arr:
    external: true

